# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-19 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_godds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Godds',
            new_name='Goods',
        ),
    ]
