# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20181121_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'cartinfo',
            },
        ),
        migrations.AlterField(
            model_name='goods',
            name='spec',
            field=models.CharField(max_length=20, verbose_name='商品规格'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Goods'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users'),
        ),
    ]
